"""
VideoCutPub - ASS (Advanced SubStation Alpha) Subtitle Generator
Converts TranscriptSegments or SRT files into styled ASS format with
support for canvas resolution, typography, colors, safe zones, and word timestamps.
"""

import os
import re
from pathlib import Path
from typing import List, Optional, Union
from pydantic import BaseModel

from ai.transcription import TranscriptSegment, TranscriptWord
from subtitles.style import SubtitleStyle, hex_to_ass_color, get_preset_style, SubtitlePresetName


def seconds_to_ass_timestamp(seconds: float) -> str:
    """
    Convertit des secondes vers le format officiel ASS : H:MM:SS.cc
    (heures, minutes sur 2 chiffres, secondes sur 2 chiffres, centièmes sur 2 chiffres).
    """
    seconds = max(0.0, seconds)
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = seconds % 60
    entire_secs = int(secs)
    centis = int(round((secs - entire_secs) * 100))
    if centis >= 100:
        entire_secs += 1
        centis = 0
        if entire_secs >= 60:
            minutes += 1
            entire_secs = 0
            if minutes >= 60:
                hours += 1
                minutes = 0
    return f"{hours}:{minutes:02d}:{entire_secs:02d}.{centis:02d}"


def srt_timestamp_to_ass_timestamp(srt_time: str) -> str:
    """
    Convertit un timestamp SRT (HH:MM:SS,mmm) vers le format ASS (H:MM:SS.cc).
    """
    srt_clean = srt_time.strip().replace(" ", "")
    parts = srt_clean.split(":")
    if len(parts) == 3:
        h = int(parts[0])
        m = int(parts[1])
        s_parts = parts[2].split(",")
        if len(s_parts) == 2:
            s = int(s_parts[0])
            millis = int(s_parts[1])
            centis = int(round(millis / 10.0))
            if centis >= 100:
                s += 1
                centis = 0
                if s >= 60:
                    m += 1
                    s = 0
                    if m >= 60:
                        h += 1
                        m = 0
            return f"{h}:{m:02d}:{s:02d}.{centis:02d}"
    return "0:00:00.00"


def parse_srt_file(srt_path: str) -> List[TranscriptSegment]:
    """
    Lit et parse un fichier .srt existant en une liste de TranscriptSegment.
    """
    path = Path(srt_path)
    if not path.is_file():
        raise FileNotFoundError(f"Fichier SRT introuvable : {srt_path}")

    content = path.read_text(encoding="utf-8", errors="replace")
    blocks = re.split(r"\n\s*\n", content.strip())

    segments: List[TranscriptSegment] = []
    idx_counter = 1

    for block in blocks:
        lines = [l.strip() for l in block.strip().splitlines() if l.strip()]
        if len(lines) >= 2:
            time_line = lines[1] if lines[0].isdigit() else lines[0]
            text_lines = lines[2:] if lines[0].isdigit() else lines[1:]

            time_match = re.match(r"(\d{2}:\d{2}:\d{2},\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2},\d{3})", time_line)
            if time_match:
                start_srt = time_match.group(1)
                end_srt = time_match.group(2)

                def srt_to_sec(st: str) -> float:
                    h, m, rest = st.split(":")
                    s, ms = rest.split(",")
                    return int(h) * 3600 + int(m) * 60 + int(s) + int(ms) / 1000.0

                start_sec = srt_to_sec(start_srt)
                end_sec = srt_to_sec(end_srt)
                text = " ".join(text_lines)

                segments.append(TranscriptSegment(
                    index=idx_counter,
                    start_sec=start_sec,
                    end_sec=end_sec,
                    start_srt=start_srt,
                    end_srt=end_srt,
                    text=text,
                    confidence=1.0,
                    words=[]
                ))
                idx_counter += 1

    return segments


class ASSGenerator:
    """Générateur de sous-titres stylisés au format Advanced SubStation Alpha (v4.00+)."""

    def __init__(self, style: Optional[SubtitleStyle] = None, width: int = 1080, height: int = 1920):
        self.width = width
        self.height = height
        self.style = style or get_preset_style(SubtitlePresetName.TIKTOK_HIGH_CONTRAST, width, height)

    def generate_ass_content(self, segments: List[TranscriptSegment]) -> str:
        """Génère la chaîne complète de texte au format .ass v4+."""
        st = self.style

        # Couleurs en format ASS (&HAABBGGRR)
        primary_ass = hex_to_ass_color(st.primary_color)
        secondary_ass = hex_to_ass_color(st.secondary_color)
        outline_ass = hex_to_ass_color(st.outline_color)
        back_ass = hex_to_ass_color(st.back_color)

        # 1. En-tête Script Info
        lines = [
            "[Script Info]",
            "; Script generated by VideoCutPub Subtitle Engine",
            "ScriptType: v4.00+",
            f"PlayResX: {self.width}",
            f"PlayResY: {self.height}",
            "WrapStyle: 0",
            "ScaledBorderAndShadow: yes",
            "",
            "[V4+ Styles]",
            "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, "
            "Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, "
            "Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
            f"Style: Default,{st.font_name},{st.font_size},{primary_ass},{secondary_ass},{outline_ass},{back_ass},"
            f"1,0,0,0,100,100,0,0,{st.border_style},{st.outline_width},{st.shadow_depth},{st.alignment},"
            f"{st.margin_l},{st.margin_r},{st.margin_v},1",
            "",
            "[Events]",
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
        ]

        # 2. Lignes d'événements (Dialogue)
        for seg in segments:
            start_ts = seconds_to_ass_timestamp(seg.start_sec)
            end_ts = seconds_to_ass_timestamp(seg.end_sec)
            
            # Formatage du texte
            text = seg.text.replace("\r\n", "\\N").replace("\n", "\\N").strip()
            if st.uppercase:
                text = text.upper()

            # Mode Karaoke / Word highlighting si configuré et disponible
            if st.highlight_current_word and seg.words and len(seg.words) > 0:
                karaoke_parts = []
                last_time = seg.start_sec
                for w in seg.words:
                    duration_centis = max(1, int(round((w.end - w.start) * 100)))
                    word_txt = w.word.strip()
                    if st.uppercase:
                        word_txt = word_txt.upper()
                    karaoke_parts.append(f"{{\\k{duration_centis}}}{word_txt}")
                text = " ".join(karaoke_parts)

            lines.append(
                f"Dialogue: 0,{start_ts},{end_ts},Default,,0,0,0,,{text}"
            )

        return "\n".join(lines) + "\n"

    def export_to_file(
        self,
        segments_or_srt: Union[List[TranscriptSegment], str, Path],
        output_ass_path: Union[str, Path]
    ) -> str:
        """
        Génère et sauvegarde le fichier .ass à partir de segments ou d'un fichier .srt existant.
        Ne modifie jamais le fichier source.
        """
        if isinstance(segments_or_srt, (str, Path)):
            segments = parse_srt_file(str(segments_or_srt))
        else:
            segments = segments_or_srt

        content = self.generate_ass_content(segments)

        out = Path(output_ass_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(content, encoding="utf-8")

        return str(out.resolve())
